### PR TITLE
Some restructuring

### PR DESCRIPTION
**Pull request by autoferrit**
Its not about the lines that were deleted, but the end result ...

Yea. So i mostly just de-cluttered some long files and made a few things easier to find. and put a few other things in dedicated files.

Yes, it works in the browser and all tests pass.

### CODE REVIEW

**Comment by ph1r3574r73r** [comment]
classifiers=[
        'Development Status :: 3 - Alpha', #what does 3 mean?
        'Framework :: AsyncIO',            #change this
        'Intended Audience :: Developers', 
        'License :: OSI Approved :: MIT License', #change this
        'Natural Language :: English',
        'Programming Language :: Python :: 3', #is 3.5 needed?
        'Programming Language :: Python :: 3.6',
        'Topic :: Internet :: WWW/HTTP', #extra comma?
    ],


also... make sure .travis.yml and run_travis.sh are updated for tests (run_travis can possibly be removed depending on what you are doing)

**Comment by autoferrit** [comment]
for classifiers:

- the `3` is an internal classifier from 1-6 i think for pypi. 3 just means it is alpha. compared to beta or whatever
- only need 3.5 if we want to support 3.5. I suggest 3.6+ as it has some nice benefits. since were early, i would like to keep on the latest. but if you want 3.5 fine. I added it in the last commit for now.
- extra comma is fine. will make additions not effect that line, technically

**Comment by ph1r3574r73r** [comment]
will accept after changes we talked about in slack

**Comment by autoferrit** [comment]
They were all committed last night.

**Pull request merged**
